FROM php:8.1-rc-fpm-alpine AS builder
ENV PHP_CFLAGS -fstack-protector-strong -fpie -O3 -fno-trapping-math -fno-semantic-interposition -falign-functions=32 -fno-lto -fno-math-errno -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
ENV PHP_CPPFLAGS ${PHP_CFLAGS}
ENV PHP_LDFLAGS -Wl,-O1 -pie
ENV PHP_BUILD_DEPS git autoconf dpkg-dev dpkg file g++ gcc libc-dev make pkgconf re2c libxml2-dev openssl-dev libedit-dev bzip2-dev curl-dev libpng-dev imagemagick-dev gmp-dev icu-dev oniguruma-dev libsodium-dev argon2-dev libzip-dev libxslt-dev
ENV PHP_APCU_SRC https://github.com/krakjoe/apcu/archive/refs/tags/v5.1.20.tar.gz
ENV PHP_XDEBUG_SRC https://github.com/xdebug/xdebug/archive/refs/tags/3.1.0beta2.tar.gz
ENV PHP_IMAGICK_SRC https://github.com/Imagick/imagick/archive/refs/tags/3.5.1.tar.gz
ENV PHP_REDIS_SRC https://github.com/phpredis/phpredis/archive/refs/tags/5.3.4.tar.gz

RUN apk update && apk upgrade && apk add --virtual .php-deps-dev ${PHP_BUILD_DEPS}
RUN docker-php-source extract
RUN mkdir -p /usr/src/imagick && cd /usr/src/imagick && curl --location ${PHP_IMAGICK_SRC} | tar xzf - --strip-components=1
RUN mkdir -p /usr/src/apcu && cd /usr/src/apcu && curl --location ${PHP_APCU_SRC} | tar xzf - --strip-components=1
RUN mkdir -p /usr/src/phpredis && cd /usr/src/phpredis && curl --location ${PHP_REDIS_SRC} | tar xzf - --strip-components=1
RUN mkdir -p /usr/src/xdebug && cd /usr/src/xdebug && curl --location ${PHP_XDEBUG_SRC} | tar xzf - --strip-components=1

WORKDIR /usr/src/php
RUN CFLAGS="${PHP_CFLAGS}" CPPFLAGS="${PHP_CPPFLAGS}" LDFLAGS="${PHP_LDFLAGS}" ./configure --enable-option-checking=fatal --build=x86_64-linux-musl \
  --prefix=/usr/local/phpbuild --with-config-file-path=/usr/local/etc/php --with-config-file-scan-dir=/usr/local/etc/php/conf.d \
  --enable-cli --enable-fpm --with-fpm-user=apache --with-fpm-group=apache --disable-cgi --disable-short-tags \
  --with-sodium --with-password-argon2 --with-openssl --with-system-ciphers \
  --enable-mysqlnd --with-pdo-mysql=mysqlnd --with-mysqli=mysqlnd --without-sqlite3 --without-pdo-sqlite \
  --with-zip --with-zlib --with-bz2 \
  --enable-bcmath --with-gmp --enable-mbstring --with-iconv \
  --enable-gd --enable-exif \
  --enable-calendar --enable-intl --enable-pcntl --enable-shmop --enable-re2c-cgoto --enable-soap --enable-sockets --with-curl --with-libedit --with-xsl 
RUN make --jobs=$(nproc) && make install
RUN cd /usr/src/imagick && phpize \
  && ./configure --with-php-config=/usr/local/phpbuild/bin/php-config --enable-option-checking=fatal \
  && make --jobs=$(nproc) \
  && make install
RUN cd /usr/src/apcu && phpize \
  && ./configure --with-php-config=/usr/local/phpbuild/bin/php-config --enable-option-checking=fatal \
  && make --jobs=$(nproc) \
  && make install
RUN cd /usr/src/phpredis && phpize \
  && ./configure --with-php-config=/usr/local/phpbuild/bin/php-config --enable-option-checking=fatal \
  && make --jobs=$(nproc) \
  && make install
RUN cd /usr/src/xdebug && phpize \
  && ./configure --with-php-config=/usr/local/phpbuild/bin/php-config --enable-option-checking=fatal \
  && make --jobs=$(nproc) \
  && make install

CMD ["/bin/sh"]

# Create the image
FROM alpine
ENV XDEBUG_REMOTE_HOST host.docker.internal
RUN apk upgrade --no-cache --purge \
  && apk add --no-cache --virtual .php-deps libxml2 openssl libedit libbz2 libcurl libpng libwebp libjpeg-turbo imagemagick gmp icu-libs oniguruma libsodium argon2-libs libzip libxslt \
  && apk add --no-cache dhcpcd apache2 apache2-proxy \
  && mkdir -p /var/www/app && chown apache:apache /var/www/app
COPY --from=builder /usr/local/phpbuild/bin/phar /usr/local/bin/
COPY --from=builder /usr/local/phpbuild/bin/phar.phar /usr/local/bin/
COPY --from=builder /usr/local/phpbuild/bin/php /usr/local/bin/
COPY --from=builder /usr/local/phpbuild/bin/php-config /usr/local/bin/
COPY --from=builder /usr/local/phpbuild/lib/php/extensions/ /usr/local/lib/php/extensions/
COPY --from=builder /usr/local/phpbuild/sbin/php-fpm /usr/local/sbin/
COPY --from=builder /usr/local/phpbuild/etc/php-fpm.d/docker.conf /usr/local/etc/php-fpm.d/docker.conf
ADD conf/php-fpm.conf /usr/local/etc/php-fpm.conf
ADD conf/php.ini /usr/local/etc/php/php.ini
ADD conf/apache.conf /etc/apache2/httpd.conf
ADD entry.sh /usr/local/bin/docker-entry.sh
ADD reload.sh /usr/local/bin/reload.sh
ENTRYPOINT ["/usr/local/bin/docker-entry.sh"]
# CMD ["--nodaemonize"]
EXPOSE 9000/tcp
EXPOSE 80/tcp
